apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: novel-recsys
  region: ap-northeast-1

availabilityZones: ["ap-northeast-1a", "ap-northeast-1c", "ap-northeast-1d"]

nodeGroups:
  - name: novel-recsys
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 2
    iam:
      withAddonPolicies:
        autoScaler: true
        albIngress: true
