version: "3"

services:
  web:
    build: ./web
    volumes:
      - ./web:/var/www
    ports:
      - "3030:3030"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    environment:
      TZ: "Asia/Tokyo"
      HOST: "container"
    tty: true
    networks:
      - narou_network

  app:
    build: ./app
    volumes:
      - ./app:/var/www/
    ports:
      - "3031:3031"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    environment:
      TZ: "Asia/Tokyo"
      HOST: "container"
    tty: true
    networks:
      - narou_network

  bertserver:
    build: ./bertserver
    volumes:
      - ./bertserver:/var/www/
    ports:
      - "3032:3032"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    environment:
      TZ: "Asia/Tokyo"
      HOST: "container"
    tty: true
    networks:
      - narou_network

  mlserver:
    build: ./mlserver
    volumes:
      - ./mlserver:/var/www/
    ports:
      - "3033:3033"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    environment:
      TZ: "Asia/Tokyo"
      HOST: "container"
    tty: true
    networks:
      - narou_network

  scraping_batch:
    build: ./scraping_batch
    volumes:
      - ./scraping_batch:/var/www
    ports:
      - "3034:3034"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    environment:
      TZ: "Asia/Tokyo"
      HOST: "container"
    tty: true
    networks:
      - narou_network

  # data_analysis:
  #   build: ./data_analysis
  #   user: root
  #   volumes:
  #     - ./data_analysis:/home/jovyan/work
  #   ports:
  #     - "10000:8888"
  #   environment:
  #     TZ: "Asia/Tokyo"
  #   tty: true
  #   networks:
  #     - narou_network

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - narou_network

  database:
    build: ./database
    hostname: database
    # env_file:
    #   - ./env_file.env
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "root"
      BIND-ADDRESS: "0.0.0.0"
    ports:
      - "3306:3306"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.{{.Name}}
    volumes:
      - ./database/mysql_init:/docker-entrypoint-initdb.d
      - ./database/mysql_data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
    tty: true
    networks:
      - narou_network

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./fluentd/log:/fluentd/log/docker_app
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - narou_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    # volumes:
    #   - ./elasticsearch/es_data:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    networks:
      - narou_network

  kibana:
    image: kibana:7.3.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    networks:
      - narou_network

networks:
    narou_network:
        external: true
