version: "3.1"


services:
  app:
    build: ./app
    volumes:
      - ./app:/var/www/
    ports:
      - 3031:3031
    environment:
      TZ: "Asia/Tokyo"
      HOST: "container"
    tty: true
    networks:
      - narou_network


  bertserver:
    build: ./bertserver
    volumes:
      - ./bertserver:/var/www/
    ports:
      - 3032:3032
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - narou_network


  mlserver:
    build: ./mlserver
    volumes:
      - ./mlserver:/var/www/
    ports:
      - 3033:3033
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - narou_network


  scraping_api:
    build: ./scraping_api
    volumes:
      - ./scraping_api:/var/www
    ports:
      - 3034:3034
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - narou_network


  elasticsearch:
    build: ./elasticsearch
    volumes:
      - ./elasticsearch/es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    tty: true
    networks:
      - narou_network


  database:
    build: ./database
    hostname: my-mysql
    env_file:
      - ./env_file.env
    environment:
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./database/mysql_init:/docker-entrypoint-initdb.d
      - ./database/mysql_data:/var/lib/mysql
      - ./database/conf.d:/etc/mysql/conf.d
    tty: true
    networks:
      - narou_network


  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    tty: true
    networks:
      - narou_network


networks:
    narou_network:
        external: true
