version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose down
          command: docker-compose down
      - run:
          name: docker-compose up
          command: python create_environment.py --build
      - run:
          name: wait to run
          command: sleep 30
      - run:
          name: web test
          command: docker-compose exec web "python /var/www/src/test/*.py"
      - run:
          name: app test
          command: docker-compose exec app "python /var/www/src/test/*.py"
      - run:
          name: bertserver test
          command: docker-compose exec bertserver "python /var/www/src/test/*.py"
      - run:
          name: mlserver test
          command: docker-compose exec mlserver "python /var/www/src/test/*.py"
      - run:
          name: scraping batch test
          command: docker-compose exec scraping_batch "python /var/www/src/test/*.py"
      - run:
          name: docker-compose down
          command: docker-compose down

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
      - run: ssh ${USER_NAME}@${HOST_NAME} 'git pull && python create_environment.py --build'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
