apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: opeco17/app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3031
        env:
        - name: HOST
          value: "container"
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
      - name: app-nginx
        image: opeco17/nginx:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_HOST
          value: "localhost:3031"
        - name: SERVER_PORT
          value: "80"
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz