apiVersion: batch/v1
kind: Job
metadata:
  name: scraping-batch
spec:
  ttlSecondsAfterFinished: 120
  completions: 1
  parallelism: 1
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: scraping-batch
        image: opeco17/scraping-batch:latest
        imagePullPolicy: IfNotPresent
        command: ["python3", "execute.py", "--test"]
        env:
        - name: HOST
          value: "container"
        - name: APP_NAME
          value: "scraping-batch"
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
      restartPolicy: Never