apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: database
  ports:
  - protocol: "TCP"
    port: 3306
    targetPort: 3306
    nodePort: 30100
  type: NodePort

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: opeco17/database:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
                name: database-secret
                key: mysql_root_password
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
        ports:
        - containerPort: 3306
          name: database
        volumeMounts:
        - name: database-volume
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: database-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5G
