apiVersion: v1
kind: Service
metadata:
  name: mlserver
spec:
  selector:
    app: mlserver
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30003
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlserver
spec:
  selector:
    matchLabels:
      app: mlserver
  replicas: 1
  template:
    metadata:
      labels:
        app: mlserver
    spec:
      containers:
      - name: mlserver
        image: opeco17/mlserver:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3033
        env:
        - name: HOST
          value: "container"
        - name: APP_NAME
          value: "mlserver"
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
      - name: mlserver-nginx
        image: opeco17/nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_HOST
          value: "localhost:3033"
        - name: SERVER_PORT
          value: "80"
        - name: TZ
          valueFrom:
            configMapKeyRef:
                name: general-config
                key: tz
